### ISSUE TITLE
Sauces are not sorted from highest to lowest

### ISSUE THREAD

**Issue by ghost** [RealKC/saucenao-discord-bot-rs#2]
![image](https://user-images.githubusercontent.com/51971218/107141792-d011ad00-6933-11eb-83df-a8261175fb6b.png)

**Comment by RealKC** [comment]
Fixed by cf245f40967aad791d29ae3b4bfef457fae2e3a5

**Comment by ghost** [comment]
still not fixed :c
![image](https://user-images.githubusercontent.com/51971218/115126835-b8f9d600-9fda-11eb-88d3-ab02d4b73fdc.png)
